[[pre-release-replacements]]
file = "CHANGELOG.md"
search = "## \\[Unreleased\\]"
replace = """## [Unreleased]\n\n## [{{version}}] - {{date}}"""
exactly = 1

[[pre-release-replacements]]
file = "CHANGELOG.md"
search = "\\.\\.\\.HEAD"
replace = "...{{tag_name}}"
exactly = 1

[[pre-release-replacements]]
file = "CHANGELOG.md"
search = "\\[Unreleased\\]: "
replace = """[Unreleased]: https://github.com/d-k-bo/opusenc-rs/compare/{{tag_name}}...HEAD\n[{{version}}]: """
exactly = 1
